# Generated by Django 5.2.8 on 2025-11-17 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Passo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "content_type",
                    models.CharField(
                        choices=[("lesson", "Lição"), ("quiz", "Quiz")],
                        default="lesson",
                        max_length=10,
                        verbose_name="Tipo de Conteúdo",
                    ),
                ),
                (
                    "text_content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Conteúdo em Texto"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="URL do Vídeo"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
            ],
            options={
                "verbose_name": "Passo",
                "verbose_name_plural": "Passos",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Questao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Texto da Questão")),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="learning.passo",
                        verbose_name="Passo (Quiz)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questão",
                "verbose_name_plural": "Questões",
            },
        ),
        migrations.CreateModel(
            name="Alternativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=255, verbose_name="Texto da Alternativa"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="É a correta?"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="learning.questao",
                        verbose_name="Questão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alternativa",
                "verbose_name_plural": "Alternativas",
            },
        ),
        migrations.CreateModel(
            name="Topico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="learning.area",
                        verbose_name="Área",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tópico",
                "verbose_name_plural": "Tópicos",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Trilha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="learning.topico",
                        verbose_name="Tópico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trilha",
                "verbose_name_plural": "Trilhas",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="passo",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="learning.trilha",
                verbose_name="Trilha",
            ),
        ),
    ]
