# Generated by Django 5.1.3 on 2025-11-17 06:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_userprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alternativa",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Alternativa",
                "verbose_name_plural": "Alternativas",
            },
        ),
        migrations.AlterModelOptions(
            name="area",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
            },
        ),
        migrations.AlterModelOptions(
            name="passo",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Passo",
                "verbose_name_plural": "Passos",
            },
        ),
        migrations.AlterModelOptions(
            name="questao",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Questão",
                "verbose_name_plural": "Questões",
            },
        ),
        migrations.AlterModelOptions(
            name="topico",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Tópico",
                "verbose_name_plural": "Tópicos",
            },
        ),
        migrations.AlterModelOptions(
            name="trilha",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Trilha",
                "verbose_name_plural": "Trilhas",
            },
        ),
        migrations.AddField(
            model_name="alternativa",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Display order (can be randomized in frontend)",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Ordem",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this learning area",
                null=True,
                verbose_name="Descrição",
            ),
        ),
        migrations.AddField(
            model_name="passo",
            name="estimated_time",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Estimated completion time in minutes",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Tempo Estimado (minutos)",
            ),
        ),
        migrations.AddField(
            model_name="questao",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="Optional explanation shown after answering",
                null=True,
                verbose_name="Explicação",
            ),
        ),
        migrations.AddField(
            model_name="questao",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Display order within the quiz",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Ordem",
            ),
        ),
        migrations.AddField(
            model_name="topico",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this topic",
                null=True,
                verbose_name="Descrição",
            ),
        ),
        migrations.AddField(
            model_name="trilha",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this track",
                null=True,
                verbose_name="Descrição",
            ),
        ),
        migrations.AddField(
            model_name="trilha",
            name="prerequisite",
            field=models.ForeignKey(
                blank=True,
                help_text="Track that must be completed before this one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unlocks",
                to="learning.trilha",
                verbose_name="Pré-requisito",
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of times user attempted this step (useful for quizzes)",
                verbose_name="Tentativas",
            ),
        ),
        migrations.AlterField(
            model_name="alternativa",
            name="is_correct",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Mark this as the correct answer",
                verbose_name="É a correta?",
            ),
        ),
        migrations.AlterField(
            model_name="alternativa",
            name="text",
            field=models.CharField(
                help_text="The choice text presented to the user",
                max_length=255,
                verbose_name="Texto da Alternativa",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Display order (lower numbers appear first)",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Ordem",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="title",
            field=models.CharField(
                db_index=True, max_length=150, unique=True, verbose_name="Título"
            ),
        ),
        migrations.AlterField(
            model_name="passo",
            name="content_type",
            field=models.CharField(
                choices=[("lesson", "Lição"), ("quiz", "Quiz")],
                db_index=True,
                default="lesson",
                max_length=10,
                verbose_name="Tipo de Conteúdo",
            ),
        ),
        migrations.AlterField(
            model_name="passo",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Display order within the track",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Ordem",
            ),
        ),
        migrations.AlterField(
            model_name="passo",
            name="text_content",
            field=models.TextField(
                blank=True,
                help_text="Main text content for lessons (supports HTML)",
                null=True,
                verbose_name="Conteúdo em Texto",
            ),
        ),
        migrations.AlterField(
            model_name="passo",
            name="title",
            field=models.CharField(
                db_index=True, max_length=150, verbose_name="Título"
            ),
        ),
        migrations.AlterField(
            model_name="passo",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube or other video embed URL",
                max_length=500,
                null=True,
                verbose_name="URL do Vídeo",
            ),
        ),
        migrations.AlterField(
            model_name="questao",
            name="text",
            field=models.TextField(
                help_text="The question text presented to the user",
                verbose_name="Texto da Questão",
            ),
        ),
        migrations.AlterField(
            model_name="topico",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Display order within the area",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Ordem",
            ),
        ),
        migrations.AlterField(
            model_name="topico",
            name="title",
            field=models.CharField(
                db_index=True, max_length=150, verbose_name="Título"
            ),
        ),
        migrations.AlterField(
            model_name="trilha",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Display order within the topic",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Ordem",
            ),
        ),
        migrations.AlterField(
            model_name="trilha",
            name="title",
            field=models.CharField(
                db_index=True, max_length=150, verbose_name="Título"
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp when the step was marked complete",
                null=True,
                verbose_name="Completado em",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="status",
            field=models.CharField(
                choices=[("completed", "Completed"), ("in_progress", "In Progress")],
                db_index=True,
                default="in_progress",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="step",
            field=models.ForeignKey(
                help_text="The step being tracked",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_progress",
                to="learning.passo",
                verbose_name="Passo",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="user",
            field=models.ForeignKey(
                help_text="The user who is progressing through the step",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="passo",
            unique_together={("track", "title")},
        ),
        migrations.AlterUniqueTogether(
            name="topico",
            unique_together={("area", "title")},
        ),
        migrations.AlterUniqueTogether(
            name="trilha",
            unique_together={("topic", "title")},
        ),
        migrations.AddIndex(
            model_name="alternativa",
            index=models.Index(
                fields=["question", "is_correct"], name="learning_al_questio_0b29bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["order", "title"], name="learning_ar_order_c66b8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passo",
            index=models.Index(
                fields=["track", "order"], name="learning_pa_track_i_6e60ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passo",
            index=models.Index(
                fields=["content_type"], name="learning_pa_content_d479d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questao",
            index=models.Index(
                fields=["step", "order"], name="learning_qu_step_id_026af8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topico",
            index=models.Index(
                fields=["area", "order"], name="learning_to_area_id_3a2980_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trilha",
            index=models.Index(
                fields=["topic", "order"], name="learning_tr_topic_i_225b2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "completed_at"], name="learning_us_user_id_973a6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["-updated_at"], name="learning_us_updated_dafafb_idx"
            ),
        ),
    ]
