# Generated by Django 5.1.3 on 2025-11-17 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_alter_alternativa_options_alter_area_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Achievement name",
                        max_length=100,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of how to earn this achievement",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("first_step", "First Step Completed"),
                            ("track_complete", "Track Completed"),
                            ("area_complete", "Area Completed"),
                            ("level_milestone", "Level Milestone"),
                            ("xp_milestone", "XP Milestone"),
                            ("streak_milestone", "Streak Milestone"),
                        ],
                        db_index=True,
                        help_text="Type of achievement",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🏆",
                        help_text="Emoji or icon identifier for this achievement",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Bonus XP awarded when earning this achievement",
                        verbose_name="Recompensa XP",
                    ),
                ),
                (
                    "required_value",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Required level/XP for milestone achievements",
                        null=True,
                        verbose_name="Valor Necessário",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order for achievements list",
                        verbose_name="Ordem",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Area this achievement is for (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.area",
                        verbose_name="Área Relacionada",
                    ),
                ),
                (
                    "related_track",
                    models.ForeignKey(
                        blank=True,
                        help_text="Track this achievement is for (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.trilha",
                        verbose_name="Trilha Relacionada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conquista",
                "verbose_name_plural": "Conquistas",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this achievement was earned",
                        verbose_name="Conquistado em",
                    ),
                ),
                (
                    "xp_awarded",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Bonus XP awarded for this achievement",
                        verbose_name="XP Concedido",
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_by",
                        to="learning.achievement",
                        verbose_name="Conquista",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conquista do Usuário",
                "verbose_name_plural": "Conquistas dos Usuários",
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "xp_points",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Total experience points earned",
                        verbose_name="Pontos de Experiência",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user this profile belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil do Usuário",
                "verbose_name_plural": "Perfis dos Usuários",
                "ordering": ["-xp_points"],
            },
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["achievement_type"], name="learning_ac_achieve_8d0963_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(fields=["order"], name="learning_ac_order_2a351d_idx"),
        ),
        migrations.AddIndex(
            model_name="userachievement",
            index=models.Index(
                fields=["user", "-earned_at"], name="learning_us_user_id_a74edd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userachievement",
            index=models.Index(
                fields=["achievement"], name="learning_us_achieve_bb5d37_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userachievement",
            unique_together={("user", "achievement")},
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["-xp_points"], name="learning_us_xp_poin_40bd23_idx"
            ),
        ),
    ]
