# Generated by Django 5.1.3 on 2025-11-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_achievement_userachievement_userprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Current consecutive days of activity",
                verbose_name="Sequência Atual",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_activity_date",
            field=models.DateField(
                blank=True,
                help_text="Date of last activity for streak tracking",
                null=True,
                verbose_name="Última Atividade",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longest_streak",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Longest streak of consecutive days",
                verbose_name="Maior Sequência",
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="achievement_type",
            field=models.CharField(
                choices=[
                    ("first_step", "Primeiro Passo Completado"),
                    ("track_complete", "Trilha Completada"),
                    ("area_complete", "Área Completada"),
                    ("rank_milestone", "Marco de Rank"),
                    ("xp_milestone", "Marco de XP"),
                    ("streak_milestone", "Marco de Sequência"),
                    ("course_badge", "Badge de Curso"),
                ],
                db_index=True,
                help_text="Type of achievement",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
