# Generated by Django 5.1.3 on 2025-11-17 08:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_userprofile_current_streak_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this provider",
                        max_length=100,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("claude", "Claude (Anthropic)"),
                            ("gemini", "Gemini (Google)"),
                            ("ollama", "Ollama (Local)"),
                            ("custom", "Custom Model"),
                        ],
                        help_text="Type of AI provider",
                        max_length=20,
                        verbose_name="Tipo de Provider",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API key for authentication (leave empty for Ollama)",
                        max_length=500,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(
                        blank=True,
                        help_text="API endpoint URL",
                        verbose_name="API Endpoint",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model identifier",
                        max_length=100,
                        verbose_name="Nome do Modelo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("max_tokens", models.PositiveIntegerField(default=2000)),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Provider",
                "verbose_name_plural": "AI Providers",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("step_lesson", "Step - Lesson"),
                            ("step_quiz", "Step - Quiz"),
                            ("quiz_questions", "Quiz Questions"),
                        ],
                        max_length=20,
                    ),
                ),
                ("system_prompt", models.TextField()),
                (
                    "user_prompt_template",
                    models.TextField(help_text="Use {{variable}} for placeholders"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Content Template",
                "verbose_name_plural": "Content Templates",
            },
        ),
        migrations.CreateModel(
            name="GeneratedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("generated_text", models.TextField()),
                ("parsed_content", models.JSONField(default=dict)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("generation_time", models.FloatField(default=0.0)),
                ("was_successful", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.aiprovider",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.contenttemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Content",
                "verbose_name_plural": "Generated Contents",
                "ordering": ["-created_at"],
            },
        ),
    ]
