# Generated by Django 5.1.3 on 2025-11-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0006_aiprovider_contenttemplate_generatedcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("claude", "Claude (Anthropic)"),
                    ("gemini", "Gemini (Google)"),
                    ("ollama", "Ollama (Local)"),
                    ("transformers", "Transformers (Hugging Face Local)"),
                    ("langchain", "LangChain"),
                    ("custom", "Custom Model"),
                ],
                help_text="Type of AI provider",
                max_length=20,
                verbose_name="Tipo de Provider",
            ),
        ),
    ]
