# Generated by Django 5.1.3 on 2025-11-17 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0007_alter_aiprovider_provider_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="passo",
            name="code_snippet",
            field=models.TextField(
                blank=True,
                help_text="Initial code template for code challenges",
                null=True,
                verbose_name="Código Inicial",
            ),
        ),
        migrations.AddField(
            model_name="passo",
            name="expected_output",
            field=models.TextField(
                blank=True,
                help_text="Expected output for code challenges",
                null=True,
                verbose_name="Saída Esperada",
            ),
        ),
        migrations.AddField(
            model_name="passo",
            name="solution",
            field=models.TextField(
                blank=True,
                help_text="Solution code (hidden from students)",
                null=True,
                verbose_name="Solução",
            ),
        ),
        migrations.AddField(
            model_name="passo",
            name="xp_reward",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="XP points awarded for completing this step",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Recompensa XP",
            ),
        ),
        migrations.AlterField(
            model_name="passo",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("lesson", "Lição"),
                    ("quiz", "Quiz"),
                    ("code_challenge", "Desafio de Código"),
                ],
                db_index=True,
                default="lesson",
                max_length=20,
                verbose_name="Tipo de Conteúdo",
            ),
        ),
    ]
