# Generated by Django 5.1.3 on 2025-11-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0008_passo_code_snippet_passo_expected_output_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_preset",
            field=models.CharField(
                blank=True,
                default="👨\u200d💻",
                help_text="Preset avatar identifier (emoji or icon name)",
                max_length=50,
                null=True,
                verbose_name="Avatar Predefinido",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="URL to user's custom avatar image",
                max_length=500,
                null=True,
                verbose_name="Avatar URL",
            ),
        ),
    ]
